# Generated by Django 4.1.2 on 2022-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="slug"),
            preserve_default=False,
        ),
    ]
